const mongoose = require('mongoose')
const schema = new mongoose.Schema({
    productId:{
        type:mongoose.Schema.Types.ObjectId,
        required:[true,"商品id不能为空"]
    },
    productName:{
        type:String,
        required:[true,"商品的名字不能为空"]
    },
    productPrice:{
      type:String,
      required:[true,"商品的价格不能为空"]
    },
    count:{
        type:Number,
        required:[true,"商品的数量不能为空"],
        min:1
    },
    totalPrice:{
        type:String,
        required:[true,"商品的总价不能为空"]
    },
    status:{
        type:String,
        default:"unpay"
    },
    created:{
      type:Date,
      default:Date.now()
    },
    pay:{
      type:Date
    },
    cancel:{
        type:Date
    }
});
module.exports = mongoose.model('orders', schema)